openapi: 3.0.3
info:
  title: LearnEng API
  termsOfService: https://swagger.io/terms/
  contact:
    email: quannguyenminh1001@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: http://localhost/api/v1
tags:
  - name: auth
    description: Mọi thứ về xác thực người dùng
  - name: topic
    description: Chủ đề
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Đăng nhập
      description: Xử lý đăng nhập
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthDTO'
        required: true
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
            application/xml:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
        '401':
          description: Tài khoản hoặc mật khẩu không đúng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 401
                message: "Tài khoản hoặc mật khẩu không đúng"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /auth/register:
    post:
      tags:
        - auth
      summary: Đăng ký
      description: Xử lý đăng nhập
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthDTO'
        required: true
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Tên đăng nhập đã tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Tên đăng nhập đã tồn tại"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /topics/{id}:
    get:
      tags:
        - topic
      summary: Lấy thông tin chủ đề theo ID
      parameters:
        - name: id
          description: Topic ID
          in: path
          required: true
          schema:
            type : string
            example: 6694e9136fe1f7bae3db86fc
      operationId: getTopic
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
            application/xml:
              schema:
                $ref: '#/components/schemas/Topic'
        '404':
          description: Không tìm thấy đề mục
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Không tìm thấy đề mục"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - petstore_auth:
            - write:pets
            - read:pets
components:
  schemas:
    BaseError:
      type: object
      properties:
        timestamp:
          type: string
          example: 2024-07-15T17:11:02.251Z
        status:
          type: integer
          example: 404
        message:
          type: string
          example: Mô tả lỗi
      xml:
        name: baseError
    LoginSuccess:
      type: object
      properties:
        refreshToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTRmMDZkMDMxZjhiMzQxZmNkZGQ5OSIsInVzZXJuYW1lIjoibWluaHF1YW56ejEwMDIiLCJpYXQiOjE3MjEwNjI5NzksImV4cCI6MTcyMjI3MjU3OX0.w8182_4ltXLseWrj0CIdNmCPVSDFfjsTq_QBqne0EfQ
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTRmMDZkMDMxZjhiMzQxZmNkZGQ5OSIsInVzZXJuYW1lIjoibWluaHF1YW56ejEwMDIiLCJpYXQiOjE3MjEwNjI5NzksImV4cCI6MTcyMTA2NjU3OX0.JrUEbhJnUH-_BAAH6EsH0EWasv6wWYVWvkpgk9hMktU
        profile:
          $ref: '#/components/schemas/UserDTO'
      xml:
        name: loginSuccess
    AuthDTO:
      type: object
      properties:
        username:
          type: string
          example: minhquanzz1002
        password:
          type: string
          example: Minh123123@
      xml:
        name: authDTO
    UserDTO:
      type: object
      properties:
        _id:
          type: string
          example: 6694f06d031f8b341fcddd99
        name:
          type: string
          example: Nguyen Minh Quan
        username:
          type: string
          example: minhquanzz1002
        status:
          type: string
          example: ACTIVE
          enum:
            - ACTIVE
            - DELETED
            - INACTIVE
        createdAt:
          type: string
          example: 2024-07-15T09:48:29.678Z
          format: date
        updatedAt:
          type: string
          example: 2024-07-15T09:48:29.678Z
          format: date
      xml:
        name: userDTO
    Topic:
      type: object
      properties:
        _id:
          type: string
          example: "6694e9136fe1f7bae3db86fc"
        name:
          type: string
          example: "Chủ đề 2"
        description:
          type: string
          example: "Mô tả"
        status:
          type: string
          enum:
            - ACTIVE
            - DELETED
            - INACTIVE
          example: "ACTIVE"
        createdAt:
          type: string
          format: date-time
          example: "2024-07-15T09:17:07.361Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-07-15T09:17:07.361Z"
      xml:
        name: topic
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:

  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header